// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUX2_If7MJahci-kz8e0CcJDLYere5FPQ',
    appId: '1:347941636138:web:4f7f1493a7048599df9b53',
    messagingSenderId: '347941636138',
    projectId: 'chat-app-ebab3',
    authDomain: 'chat-app-ebab3.firebaseapp.com',
    storageBucket: 'chat-app-ebab3.firebasestorage.app',
    measurementId: 'G-JXLZ6VFWD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKApMIWsMcF2JnbjH9m5hg9Dc4yRc4vwk',
    appId: '1:347941636138:android:e9ef3a834c20c46fdf9b53',
    messagingSenderId: '347941636138',
    projectId: 'chat-app-ebab3',
    storageBucket: 'chat-app-ebab3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB05FOqT_qiml7TqrCqueCUWefqwVrWn1U',
    appId: '1:347941636138:ios:f038418e9f4f01ccdf9b53',
    messagingSenderId: '347941636138',
    projectId: 'chat-app-ebab3',
    storageBucket: 'chat-app-ebab3.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB05FOqT_qiml7TqrCqueCUWefqwVrWn1U',
    appId: '1:347941636138:ios:f038418e9f4f01ccdf9b53',
    messagingSenderId: '347941636138',
    projectId: 'chat-app-ebab3',
    storageBucket: 'chat-app-ebab3.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUX2_If7MJahci-kz8e0CcJDLYere5FPQ',
    appId: '1:347941636138:web:43dd45cc7a328c69df9b53',
    messagingSenderId: '347941636138',
    projectId: 'chat-app-ebab3',
    authDomain: 'chat-app-ebab3.firebaseapp.com',
    storageBucket: 'chat-app-ebab3.firebasestorage.app',
    measurementId: 'G-KWQFK6C9D4',
  );

}